import type { Metadata } from "next";
import "./globals.css";
import { russo, outfit, kodeMono } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${russo.variable} ${outfit.variable} ${kodeMono.variable} overflow-hidden`}
    >
      <body className="bg-black text-white">{children}</body>
    </html>
  );
}
